import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider appearance= {{
              layout: {
                // Desativa a navegação e o header do Clerk
                socialButtonsVariant: "iconButton",
                showOptionalFields: false
              },
              elements: {
                // Personalização opcional adicional
                card: 'rounded-lg shadow-md',
                formButtonPrimary: 'bg-[#69DC9E] hover:bg-[#004a7c]',
                // Esconde especificamente o header
                navbar: false,
                navbarButtons: false
              }
      }}>
        <html>
          <body>{children}</body>
        </html>
    </ClerkProvider>
  )
}